### ISSUE TITLE
Create a seperate folder for all these file

### ISSUE THREAD

**Issue by Skywalkers-24** [Skywalkers-24/Hactoberfest-2020-native#17]
Make a folder and move all these files into it

**Comment by prpwien** [comment]
Hey, I'd like to do this! Could you please assign me to this issue?

**Comment by peace-25** [comment]
Could you please assign this issue to me? I'd like to work on it.

**Comment by Skywalkers-24** [comment]
YES

**Comment by Skywalkers-24** [comment]
>  @peace-25 thanks
